name: Generate tokens

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.13
      - name: Install Node Dependencies
        run: npm ci
      # Transform Figma Tokens JSON to something Style Dictionary can read, then
      # Convert tokens according to Style Dictionary config
      - name: Build Style Dictionary
        run: npm run tokens:build
      # Add files that were created during a run, e.g. created files from Style
      # Dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
